title: Mon Site
icon: logo.svg
search: True
theme: True
content:
  mes projets:
    icon: project.svg
    content:
      projetA:
        icon: projA.svg
        content: projetA.md
      projetB:
        icon: projB.svg
        content: projetB.md
      projetC:
        debut:
          icon: debut.svg
          content: debut.md
        fin:
          icon: fin.svg
          content: fin.md
  mon parcours:
    content: parcours.md